### Set the base image to the one built before
FROM tomcat:8.0

### File Author / Maintainer
MAINTAINER "Andreas Neeb" "aneeb@redhat.com"

### Add application to Tomcat 
COPY app/sample.war /usr/local/tomcat/webapps/ 
