### Set the base image
FROM eap64

### File Author / Maintainer
MAINTAINER "Andreas Neeb" "aneeb@redhat.com"

### Add application to JBoss EAP
COPY app/ticket-monster.war $JBOSS_HOME/standalone/deployments/
