FROM registry.access.redhat.com/rhscl/httpd-24-rhel7

LABEL maintainer="aneeb@redhat.com"
ARG IMAGE_VERSION=0.1

# In vivo we would do something useful here
# Simply setting image version for now
RUN echo ${IMAGE_VERSION} > /opt/app-root/src/image-version
